services:
  musicmetacleaner:
    image: ${DOCKERHUB_USERNAME:-anyear}/music-metac-leaner:${IMAGE_TAG:-latest}
    container_name: music-metac-leaner
    pull_policy: always
    ports:
      - "${HOST_PORT:-5000}:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    restart: unless-stopped
